### ISSUE TITLE
Incorrect project id reference in documentation.

### ISSUE THREAD

**Issue by julianhall** [tick/tick-api#11]
Hi Guys - in tick-api/sections/projects.md 

under the Get project explanation you use id 16 (GET /projects/16.json)
But in the tasks section it references its tasks as 14
...
"url":"https://www.tickspot.com/api/v2/123/projects/14/tasks.json",
...

**Comment by tick** [comment]
Thanks!  I've updated the sample data...

**Comment by julianhall** [comment]
Great thanks.
