### ISSUE TITLE
Entries pagination not working

### ISSUE THREAD

**Issue by robertofrega** [tick/tick-api#12]
I am currently developing an app that consolidates our billable hours per project and per user (each user has a different hourly rate).

We are fetching entries by project, but the entries endpoint does not seem to work with pagination.
Nor does the result seem to follow any standard order we could use to paginate.

How is pagination suppose to work on that end point?

**Comment by tomrossi7** [comment]
The pagination is described here: https://github.com/tick/tick-api#pagination. The entries are returned 100/request. I'm not sure what your specific problem may be, but let me know and I can try and help.

**Comment by robertofrega** [comment]
Sorry, I think we might have ran into a glitch... We tried to reproduce the error but it's working fine now.

**Comment by tomrossi7** [comment]
No problem! Let us know if you need anything else...
