### ISSUE TITLE
Question / feature request: entered hours for all projects

### ISSUE THREAD

**Issue by jason-ld** [tick/tick-api#13]
Hi there,

I've been using this API for a bit and it has been great in terms of automation.

There's [GET /projects](https://github.com/tick/tick-api/blob/master/sections/projects.md#get-projects) that returns a list of all open projects and then there's [GET /projects/xx](https://github.com/tick/tick-api/blob/master/sections/projects.md#get-project) for an individual project.

While GET /projects and GET /projects/xx both include `budget` of a project, is there a reason why only GET /projects/xx includes `total_hours` but GET /projects doesn't? 

The same thing also applies for [GET /tasks](https://github.com/tick/tick-api/blob/master/sections/tasks.md#get-tasks) and [GET /tasks/xx](https://github.com/tick/tick-api/blob/master/sections/tasks.md#get-task)

Thanks!

**Comment by tick** [comment]
Hi Jason! The GET /projects method can return thousands of projects, while the GET /projects/id method will only return one project. For reasons of performance, we can do things on the one method that we can't do on the other. Another good example is that we can return the list of tasks when you are request just the one project. I hope that makes sense!

**Comment by jason-ld** [comment]
Cool, makes sense!

So if I were to create a dashboard that lists all of my open projects, the budget and total hours spent: I'd use the GET /projects method to get my open projects and budget, then for each open project, call GET /projects/id to get the total hours spent?

**Comment by tick** [comment]
Sure thing! For a dashboard, you may also want to check out the /entries method using the "updated_at" to bring back the latest entries. Thanks for using Tick's API!

**Comment by jason-ld** [comment]
I'll check them out, thanks a lot!
