### ISSUE TITLE
New entry returns "Missing required parameters"

### ISSUE THREAD

**Issue by wjvdhoek** [tick/tick-api#15]
Requesting (private data masked ofcourse) :
```
POST /xxxxx/api/v2/entries.json HTTP/1.1
Authorization: Token token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Host: www.tickspot.com
Content-Length: 143
User-Agent: TestApp(zzz@yyyy.xxx)
X-Target-URI: https://www.tickspot.com
Content-Type: text/plain; charset=UTF-8
Connection: Keep-Alive

{
  "date": "2016-06-28",
  "hours": 1.5,
  "notes": "Test note",
  "task_id": xxxx,
  "user_id": xxxx
}
```

results in a `HTTP/1.1 400 Bad Request` with the message `Missing required parameters`

The documentation does not make note of any required parameters?

**Comment by tomrossi7** [comment]
I just looked into this and our documentation does not appear to be correct. Your JSON will require the root object:

{ 
 entry: {
   "date": "2016-06-28",
   "hours": 1.5,
   "notes": "Test note",
   "task_id": xxxx,
   "user_id": xxxx
  }
}

Please give that a try and update this ticket. Sorry for the hassle!

**Comment by wjvdhoek** [comment]
Thnx for the quick response! Unfortunetely I'm still getting a `400 Bad Request`...

I've included the full response, maybe that'll be of some help:

```
HTTP/1.1 400 Bad Request
X-Runtime: 0.012658
Content-Length: 27
X-XSS-Protection: 1; mode=block
X-UA-Compatible: chrome=1
X-Request-Id: d46eefd3-1ed0-46b8-88c2-3b9b723101cb
Connection: keep-alive
X-Powered-By: Phusion Passenger 4.0.45
Server: Apache/2.4.7 (Ubuntu)
X-Content-Type-Options: nosniff
Cache-Control: no-cache
Status: 400 Bad Request
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=31536000
Date: Wed, 29 Jun 2016 14:03:35 GMT
Content-Type: application/json; charset=utf-8

Missing required parameters
```

**Comment by tomrossi7** [comment]
What did you use for your body?

You may need quotes on entry for proper json:

```
{ 
 "entry": {
   "date": "2016-06-28",
   "hours": 1.5,
   "notes": "Test note",
   "task_id": xxxx,
   "user_id": xxxx
  }
}
```

**Comment by wjvdhoek** [comment]
The body looks like this:
```
{ 
    "entry": {
        "date":"2016-06-28",
        "hours":1.5,
        "notes":"Test note",
        "task_id":xxxx,
        "user_id":xxxx
    }
}
```

`task_id` and `user_id` are numeric values and not between quotes.

**Comment by wjvdhoek** [comment]
@tomrossi7 Found it! The `Content-Type: application/json` is mandatory.

I'm greeted with the following response:
```
HTTP/1.1 201 Created

{
  "id": xxx,
  "date": "2016-06-28",
  "hours": 1.5,
  "notes": "Test note",
  "task_id": xxx,
  "user_id": xxx,
  "url": "https://www.tickspot.com/xxx/api/v2/entries/xxx.json",
  "created_at": "2016-06-29T11:00:44.322-04:00",
  "updated_at": "2016-06-29T11:00:44.322-04:00"
}
```

Maybe the documentation should be updated?

**Comment by tomrossi7** [comment]
The content type is not a required header. You should be able to remove it completely and it would work. It looks like you may have been posting with Content-Type: text/plain; charset=UTF-8.

The documentation still needs to be updated to make sure that the root is set for all object creations within the API.

**Comment by wjvdhoek** [comment]
The API console I'm using (Apigee) inserts the Content-Type header automatically. Anything other than `application/json` results in an error.

**Comment by justindra** [comment]
I seem to be having a similar problem.

```
{
	"entry": {
	  "date":"2017-08-16",
	  "hours":8,
	  "notes":"something here",
	  "task_id":xxx,
	  "user_id":xxx
	}
}
```

and it returns the following:
```
Cache-Control →no-cache
Connection →close
Content-Length →128
Content-Type →application/json; charset=utf-8
Date →Thu, 03 Aug 2017 23:16:13 GMT
Server →Apache
Status →401 Unauthorized
Strict-Transport-Security →max-age=31536000
WWW-Authenticate →Token realm="Application"
X-Content-Type-Options →nosniff
X-Frame-Options →SAMEORIGIN
X-Request-Id →969d2993-652f-4b17-867e-743138b19122
X-Runtime →0.005022
X-UA-Compatible →chrome=1
X-XSS-Protection →1; mode=block
```

```
Unexpected 'R'
```

I am just using the token given from the `roles` endpoint

**Comment by justindra** [comment]
Actually full raw message:
```
Rejected user agent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36'
```

**Comment by tick** [comment]
Yes, your user agent is incorrect: https://github.com/tick/tick-api#user-agent. Let us know if you still have questions.

**Comment by justindra** [comment]
So what user agents are actually allowed?

**Comment by johnlpollard** [comment]
Any user agent that has an email address should work.

**Comment by justindra** [comment]
Ah yep, thanks
