### ISSUE TITLE
Update entry returns "Missing required parameters"

### ISSUE THREAD

**Issue by markbiek** [tick/tick-api#16]
I'm sending a PUT request to `https://www.tickspot.com/xxxxx/api/v2/entries/xxxxx.json` using command-line cURL and I keep getting *Missing required parameters*.

It's not completely obvious from the documentation what the required parameters are but I've tried various combinations of _hours_, _user_id_, _task_id_, and _billed_ and nothing seems to work.

Is this an issue or am I just doing something dumb?

The complete cURL command is:

```
curl -X PUT -d hours=2 -d user_id=xxxxx -d task_id=xxxxx -d billed=true -H "User-Agent: Timetrot (me@me.com)" -H 'Authorization: Token token=xxxxx' https://www.tickspot.com/xxxxx/api/v2/entries/xxxxx.json
```

**Comment by markbiek** [comment]
Sigh. Looks like my original request was malformed. This works nicely:

```
curl -X PUT -d '{"user_id": xxxxx,"hours":1}' -H 'Content-Type: application/json' -H "User-Agent: Timetrot (me@me.com)" -H 'Authorization: Token token=xxxxx' https://www.tickspot.com/xxxxx/api/v2/entries/xxxxx.json
```

Sorry for the confusion

**Comment by tomrossi7** [comment]
No problem @markbiek! Just let us know if you need anything!
