### ISSUE TITLE
Bad Credentials only on Google Apps Script

### ISSUE THREAD

**Issue by robertofrega** [tick/tick-api#17]
I get the response "Bad credentials or user agent" for every single request, but only on Google Apps Scripts. We checked and the credentials are correct. Any known bugs? Maybe your firewall blocked requests coming from GApps?

**Comment by tick** [comment]
Are you setting the User Agent correctly?

**Comment by robertofrega** [comment]
Yep. Everything is exactly the same on both backends. I ended up using one
to proxy for the other.

**Comment by tomrossi7** [comment]
Something must be different. The error you are seeing will only show up if the email, password, user agent have an issue. We can look at the logs if you email into support after making a failed request.

**Comment by tomrossi7** [comment]
@robertofrega Did you get this worked out?

**Comment by robertofrega** [comment]
@tomrossi7 In a way, but not really. I ended up using an intermediate server and it is working fine now. I still believe it might be a problem on your end, though. Might be worth a check ;)

**Comment by tomrossi7** [comment]
This was fixed by adding the Google Script user agent to the approved user agents.
