### ISSUE TITLE
How to fetch closed tasks

### ISSUE THREAD

**Issue by nickolaj** [tick/tick-api#18]
Hi

I can't find a documented way to extract closed tasks - can you help me out (might be stronger glasses is whats needed)?

**Comment by tomrossi7** [comment]
No stronger glasses necessary! We really need to add a **closed** API endpoint to return those tasks that are closed.

**Comment by andrelangeLait** [comment]
Any news on this ? Being able to fetch closed tasks is a really needed feature.

**Comment by tick** [comment]
Sorry no news! Hasn't made it up our priority list.

**Comment by jadcsi** [comment]
I would like to further up-vote for this enhancement

**Comment by Frederikbh** [comment]
Any news on this?

**Comment by johnloringpollard** [comment]
Hey everyone I added a `tasks/closed.json` method for you to retrieve all closed tasks. It works with a project ID just like the index method.

**Comment by Frederikbh** [comment]
Thank you very much!

I can't get it working with a project ID however - I assume you mean:
GET /projects/16/tasks/closed.json

Also, the closed tasks has a null-value for date_closed.

**Comment by johnloringpollard** [comment]
Yes, you have the correct URL. There was an issue that I fixed and deployed, so everything should work now. 

A task that isn't closed itself can still be closed because the associated project was closed. So if a task has a null value for date closed, it's because the project was closed.
