### ISSUE TITLE
Provide deleted users on /users.json

### ISSUE THREAD

**Issue by robertofrega** [tick/tick-api#20]
Even though the UI shows the names for deleted users, the endpoint only returns the ones that are still active. Is there a way to force de endpoint to return those deleted users? a flag maybe? (`show_deleted=true`)

**Comment by tomrossi7** [comment]
What information are you trying to access related to an user that is no longer active on your subscription? The complexity comes from the fact that a user may still have another Tick subscription they are using.

**Comment by gbanasiak** [comment]
I have exactly the same issue, and the information I'm trying to retrieve for deleted user is first name and last name. I need this to correlate Tickspot data with external data sources (Tickspot ID is meaningless outside of Tickspot).

**Comment by johnloringpollard** [comment]
You can now call users/deleted to retrieve users that have time entries but no longer have subscription access. This only works for admins.

**Comment by gbanasiak** [comment]
"users/deleted.json" was exactly the thing I was looking for. thanks.
