### ISSUE TITLE
unable to close projects.

### ISSUE THREAD

**Issue by andrelangeLait** [tick/tick-api#21]
i am unable to close projects, when i send a request, i receive a 204 "no content".
this is how my request url looks.
`https://www.tickspot.com/{SubscriptionID}/api/v2/projects/{ProjectID}.json`

and i am sending json instructions where i update `date_closed = "2017-01-05" `

am i not able to close projects this way ?

**Comment by tomrossi7** [comment]
Yes, you are doing that correctly! A 204 means you have successfully updated the resource:

> 204 NO CONTENT - The server has successfully fulfilled the request and that there is no additional content to send in the response payload body.

**Comment by tomrossi7** [comment]
Can you email support@tickspot.com with the project id you are updating so we can investigate further?

**Comment by andrelangeLait** [comment]
yes, i will do that.

**Comment by andrelangeLait** [comment]
this was resolved over email.
