### ISSUE TITLE
Communication With API rejecting request

### ISSUE THREAD

**Issue by highimpactDev** [tick/tick-api#22]
As of Friday 1/13/17 my requests to Tickspot are being rejected. I get a "The request was aborted: Could not create SSL/TLS secure channel." I have checked the API token and the Subscription ID and they bother are correct. Did something change from 1/12/17 to 1/13/17. Because everything was working fine on 1/12. I've submitted a request to your helpdesk with no response. I need help diagnosing this issue as soon as possible so I can get our company tools that relies on the information from Tickspot back up and running.

Thanks
Dieter

**Comment by highimpactDev** [comment]
I figured out the issue. I added this line to my code and everything started working again ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12. Not sure when things changed on your end but as I said in my previous post everything was working fine last Thursday.

Thanks
Dieter

**Comment by tick** [comment]
Sorry @highimpactDev , we updated the SSL requirements and you must have been using an older protocol. I'm glad you figured it out!
