### ISSUE TITLE
Not Clients returning if have no Associated Projects

### ISSUE THREAD

**Issue by jadcsi** [tick/tick-api#23]
I am trying to execute https://www.tickspot.com/{subscription_id}/api/v2/clients.json and not getting the client if it doesn't have any projects associated with it.  The client is created via the API so that is how this could occur.  This is part of an attempt to migrate data from a homegrown time tracking system into Tick

**Comment by tick** [comment]
Yes, [the /clients endpoint](https://github.com/tick/tick-api/blob/master/sections/clients.md#get-clients) will return all the clients that have opened projects. You can [access the specific client](https://github.com/tick/tick-api/blob/master/sections/clients.md#get-client), by using the id of the [newly created client returned in the location header](https://github.com/tick/tick-api/blob/master/sections/clients.md#create-client).
