### ISSUE TITLE
Update entry not returning entry's JSON

### ISSUE THREAD

**Issue by jadcsi** [tick/tick-api#24]
I am seeing that the documentation is incorrect in stating that the JSON of the entry is returned after the update is successful.  Instead I am seeing an empty body and HTTP return code 204

**Comment by johnloringpollard** [comment]
Can you show me an example of your request? The documentation is correct, you should get an HTTP code of 200 and the object details in the body.

**Comment by jadcsi** [comment]
I just executed

https://www.tickspot.com/94114/api/v2/entries/57596066.json
to increase the time from 8.0 to 9.0 with JSON body:
{"date":"2017-03-08","hours":9.0,"notes":"Debugging issues about Publishing
to Koverse.  ","task_id":9519852,"user_id":267390}

It is successful yet I am returned no content and HTTP 204

**Comment by johnloringpollard** [comment]
Hey @jadcsi, you were correct. Not sure why ruby was doing that but I forced the response. You should be all set now. Thanks for letting us know.
