### ISSUE TITLE
Getting 400 Bad Request when using PUT method for updating project

### ISSUE THREAD

**Issue by nekromoff** [tick/tick-api#29]
Empty response: `400 Bad Request`

https://www.tickspot.com/XXXXX/api/v2/projects/PROJECTID.json

payload:
```
utf8:✓
billable:true
client_id:5
```

**Comment by jjjpppp** [comment]
If you look at the documenation, the payload has to go into a projects param. 

```
{
  "project":
    {
      "budget":300,
      "billable":true
     }
}
```

**Comment by nekromoff** [comment]
this works, thanks
