### ISSUE TITLE
/users.json pagination not working properly

### ISSUE THREAD

**Issue by tbouranis** [tick/tick-api#30]
While testing the /users.json endpoint in Postman, I found that querying the page number has no effect. That is, /users.json?page=1 returns the array of my users as expected, but /users.json?page=2, /users.json?page=3, etc return the exact same array of users as ?page=1. In testing arbitrarily large numbers of pages, the empty array was never returned.

Is this inconsistency with the paginated results of every other endpoint intentional? Or is the /users.json endpoint working incorrectly? If I have over 100 users, will /users.json return all of them in a single call?

**Comment by tick** [comment]
The users endpoint does not paginate, so if you had more than 100 users, they would all be returned in a single call.
