### ISSUE TITLE
Retrieving entries from wide ranges of params

### ISSUE THREAD

**Issue by vizigin** [tick/tick-api#31]
We have got ~60 projects per month.
I would like to get entries from all projects in one query. 
How I can do that?

**Comment by johnlpollard** [comment]
Check out the documentation we have for getting entries. Don't forget about pagination too!

GET /entries.json will return all time entries that meet the provided parameters

**Comment by vizigin** [comment]
I would like to group all projects after retrieve, but Entry's object doesn't have project_id field :(

**Comment by johnlpollard** [comment]
Sorry at this time only provide the id of the first relative object. You will need to do a GET for the task and a GET for the project. It's pretty simple to get though since it's following the RESful conventions.

**Comment by vizigin** [comment]
My goal is report like this:
Project 1  |  2 hours
- User 1   |  1 hour
- User 2  |  1 hour (spent time)

If I do a GET task and a GET for the project, I can't get time entry in query. Task doesn't contain spent time. Entries contains spent time only. For complete this goal, I should to do a large number of queries from 60 projects or all tasks of this 60 projects ¯\_(ツ)_/¯

**Comment by johnlpollard** [comment]
I would do a GET entries for the time period you need, store an array of all the task ids, do a GET for each task id, store an array of project ids, then do a GET for each of those projects. This will take a large number of queries to our database but it's fast so it should handle it! :) Sorry but at this time we don't have a way to retrieve all info with just one query.

**Comment by vizigin** [comment]
@johnlpollard okay, I got it
