### ISSUE TITLE
Getting projects for a client

### ISSUE THREAD

**Issue by thepaleone** [tick/tick-api#34]
We've been using this for years but suddenly the following URL structure started returning a **406 Unacceptable** result. Is this no longer a valid method?

`https://secure.tickspot.com/<removedId>/api/v2/clients/<removedclientid>/projects`

**Comment by thepaleone** [comment]
I should note, this is the value from the projects.url property returned by the /client.json method.

**Comment by johnlpollard** [comment]
We just updated our codebase. Let me take a look now.

**Comment by johnlpollard** [comment]
Can you try again now?

**Comment by thepaleone** [comment]
It seems to be working now. Whatever you did appears to have resolved it. Thank you for the quick response!

**Comment by johnlpollard** [comment]
The URL was missing the JSON format. Thanks for letting us know!
