### ISSUE TITLE
Create User via POST

### ISSUE THREAD

**Issue by SparkInChief** [tick/tick-api#36]
This is a feature request.

I would like to automatically add a team member to Tick when they are added to our Google for Nonprofits account. I can handle crafting the payload, but there isn't currently a **Create User** endpoint.

Will you add a method to `users.json` to allow user creation via POST the same way entries/tasks/projects/clients are created? I would expect response/error messages to be similar to what happens in the UI (e.g. "that user already exists", etc.)

This would make my workflow so simple by taking out one of the last "manual onboarding" steps!

**Comment by underpope** [comment]
I second this. We're in the process of converting our entire project history database to Tick, and we have nearly a hundred users, past and present, that we need to add to Tick.

**Comment by johnlpollard** [comment]
We are going to take a look at possibly adding this. I'll let you know what we find and come up with!

**Comment by johnlpollard** [comment]
We have added the ability to create users. Let me know how this works for you!

https://github.com/tick/tick-api/blob/master/sections/users.md#create-user

**Comment by underpope** [comment]
Thanks for responding so rapidly!

Will users created via POST receive notification of their new account? My preference is for them not to right now.

**Comment by johnlpollard** [comment]
Yes, users will receive an invitation email. We have to send the email to the users for them to receive their temporary login credentials.

**Comment by SparkInChief** [comment]
You’re heroic. Thank you so much for doing this!

**Comment by SparkInChief** [comment]
@johnlpollard When I hit https://www.tickspot.com/xxxxx/api/v2/users.json via `GET`, the list of users in my project is returned as expected. 

When I `POST` a payload to the same endpoint, I get a **404 Not Found** response. 

```
POST /xxxxx/api/v2/users.json HTTP/1.1
Host: www.tickspot.com
Authorization: Token token=xxxxx
User-Agent: Custom App (admin@example.org)
Content-Type: application/json
Cache-Control: no-cache


{
  "user":
  {
    "first_name":"New",
    "last_name":"Staff",
    "email":"new-staff-example@example.org",
    "admin":"false",
    "billable_rate": "100.0"
  }
}
```
Aside from changing identifying stuff, this is exactly what is being sent. Am I missing something obvious?

**Comment by johnlpollard** [comment]
Can you try again now?

**Comment by SparkInChief** [comment]
Beautiful. It worked without changing anything above. Thanks again!
