### ISSUE TITLE
User created via API gets invitation email from self

### ISSUE THREAD

**Issue by SparkInChief** [tick/tick-api#38]
### Repro Steps

Using the API key of an admin user, Post the following payload to `users.json`:
```json
{ 
"user":
  {
   "first_name":"Anakin",
   "last_name":"Skywalker",
   "email":"anakin@egjarts.org",
   "admin":"false",
   "billable_rate": "100.0"
  }
}
```

### Expected result:

The user receives an invitation email referencing the admin user whose API token was used, just as if the user had been added through the Tick web UI. It should begin with

> Hello Anakin Skywalker,
> 
> SparkInChief has invited you to the **Empire & Great Jones Creative Arts Foundation** Tick account, welcome!

as seen here:
![image](https://user-images.githubusercontent.com/20958704/34801402-6412a9d8-f61d-11e7-952b-4ab2dffaffe4.png)

### Actual result:

The user receives an invitation email with their own name that begins with

> Hello Anakin Skywalker,
> 
> Anakin has invited you to the **Empire & Great Jones Creative Arts Foundation** Tick account, welcome!

as seen here:
![image](https://user-images.githubusercontent.com/20958704/34801564-3c32e404-f61e-11e7-85ed-55ac0fca239a.png)

**Comment by SparkInChief** [comment]
This is obviously a super-low-priority bug but since it affects the overall polish of Tick I wanted you to know!

**Comment by johnlpollard** [comment]
This should be fixed!
