### ISSUE TITLE
Authentication problem - Bad credentials

### ISSUE THREAD

**Issue by kredmer** [tick/tick-api#4]
I am not able to connect to your api.

I tried:

https://www.tickspot.com/999999999/api/v2/projects.json
with headers:
Authorization: Token mytoken
User-Agent: testapp (mymail)

At the top of doc:
All URLs start with https://www.tickspot.com/9999/api/v2/     ( 4 times 9 )
Authorization: Token ApV99yzvwApV99yzvwApV99yzvwApV99yzvw (Token with whitespace separated)

Sample get:
 https://www.tickspot.com/999999999/api/v2/projects.json (9 times 9)
curl -H "Authorization: Token token=ApV99yzvwApV99yzvwApV99yzvwApV99yzvw"  (Token with whitespace and then assigning token with the token.

I am not able to get it to work.
Any ideas?

**Comment by tomrossi7** [comment]
You have to use your own token, and the correct subscription_id for your account.  Check out the documentation at https://github.com/tick/tick-api/blob/master/sections/roles.md.

**Comment by jcvela76** [comment]
Hi 

Do you any example code in PHP?

Thanks

Julio V
