### ISSUE TITLE
Deleted User Pagiantion

### ISSUE THREAD

**Issue by mrosenberg** [tick/tick-api#40]
The /users/deleted.json endpoint doesn't follow the same pagination rules as other endpoints. Looping the endpoint and incrementing the page query param will return the same list of results instead of an empty array like tasks, entries, etc.

**Comment by johnlpollard** [comment]
Hey @mrosenberg. That is correct. We return the entire result set in the response to make it simpler. The thinking is that you don't need to paginate because you're not going to have 500+ deleted users. Most have only a few if any.

**Comment by mrosenberg** [comment]
Thanks, for following up. I didn't see your response until just now. While that is probably true about a limited number of deleted users it would still be helpful to have the endpoint follow the same pagination rules as the other collections.
