### ISSUE TITLE
projects.json only bringing in active projects

### ISSUE THREAD

**Issue by kgalyen** [tick/tick-api#44]
I'm not seeing anything in the documentation about bringing in archived projects when requesting projects.json

There is a field for "date_closed", but even projects I own aren't there if they are closed.

**Comment by tomrossi7** [comment]
Sorry @kgalyen ! Archived projects are also called closed projects and they can be accessed using the `GET /projects/closed.json` endpoint described [here](https://github.com/tick/tick-api/blob/master/sections/projects.md#get-projects). Please let us know if you still have questions!

**Comment by kgalyen** [comment]
Thanks so much! I think I didn't realize there was more to the documentation than what I was seeing. Thank you!

**Comment by tomrossi7** [comment]
It's no problem at all!
