### ISSUE TITLE
url in responses no longer valid

### ISSUE THREAD

**Issue by jacobpledger** [tick/tick-api#49]
Querying https://www.tickspot.com/$subscription/api/v2/projects.json returns entries with a key/value: `"url": "http://secure.tickspot.com/$subscription/api/v2/projects/$project.json"`, but now I am suddenly getting authentication issues when using those urls for subsequent queries. I have to instead use the `https://www.tickspot.com/$subscription/api/v2/` stub and extract the useful bits myself.

**Comment by tomrossi7** [comment]
Can you email support with the details? We completed some server upgrades this week and I want to make sure we didn't miss something!

**Comment by jacobpledger** [comment]
Done. Thanks for the swift response. I can't give an exact estimate of when this happened, sadly, I don't know how "sudden" this sudden issue was.

**Comment by tomrossi7** [comment]
The URL being returned should have been `https` not `http`. The URL will work with `www.` or `secure.` as the subdomain. I've just deployed a fix. Thanks for reporting the issue!

**Comment by jacobpledger** [comment]
No problem, thanks for fixing it - I just confirmed it on my end.
