### ISSUE TITLE
Could you clarify how to get a token?

### ISSUE THREAD

**Issue by MiraD1n** [tick/tick-api#52]
Could you clarify how to get a token?

**Comment by johnloringpollard** [comment]
In your Tick account, click on Account from the top right navigation, click on "Edit Profile". Then on the right side of the screen, you will see your API information including your token.

**Comment by MiraD1n** [comment]
It is a pity, but I see only account settings

[![Screenshot-2.jpg](https://i.postimg.cc/sDwTYcVx/Screenshot-2.jpg)](https://postimg.cc/LngkRjgF)
[![Screenshot-4.jpg](https://i.postimg.cc/tCSzZ45V/Screenshot-4.jpg)](https://postimg.cc/3dGGz7zK)

**Comment by johnloringpollard** [comment]
I'm not sure what app that is but you should go to https://secure.tickspot.com/login and login to get your credentials.

**Comment by MiraD1n** [comment]
OU. I'm very sorry to bother you. This is not the right application. I missed. Thank you very much for your prompt feedback. I thought it Tick-Tick https://ticktick.com/webapp
