### ISSUE TITLE
Cannot create a user with `admin` and `billable_rate` fields

### ISSUE THREAD

**Issue by miguelnietoa** [tick/tick-api#56]
### Description

It seems that the `admin` and `billable_rate` fields are being ignored by the API. 

- **Request Body:**
```
{
  "first_name": "John",
  "last_name": "Doe",
  "email": "jd@tickspot.com",
  "admin": true,
  "billable_rate": 10.0
}
```

- **Request Response:**
```
{
  "id": 486358,
  "first_name": "John",
  "last_name": "Doe",
  "email": "jd@tickspot.com",
  "timezone": "Eastern Time (US & Canada)",
  "created_at": "2022-08-04T11:27:09.000-04:00",
  "updated_at": "2022-08-04T11:27:09.000-04:00"
}
```

---

Checking on the website, the user is created but it is not an admin and has no billable rate set.
- **Screenshot:**
![image](https://user-images.githubusercontent.com/39246879/182888970-ee4c8638-e958-4143-a598-820789694666.png)

### Questions
- How can I create an administrator user? 
- How can I create a user with a billable rate set?

https://github.com/tick/tick-api/blob/master/sections/users.md#create-user

**Comment by johnloringpollard** [comment]
First, you are sending with the root as "user" right? 
```
"user":
   {
    "first_name":"Anakin",
    "last_name":"Skywalker",
    "email":"admin@tickspot.com",
    "admin":"true",
    "billable_rate": "100.0"
   }
 }
```

If so, can you try sending the admin and billable rate parameters as a string to see if that works for you?

**Comment by miguelnietoa** [comment]
I was missing sending the data with the root as "user". Now works! 🤟🏻 
Thanks a lot @johnloringpollard!
