### ISSUE TITLE
Token Auth example incorrect

### ISSUE THREAD

**Issue by jrobgood** [tick/tick-api#6]
The Authentication section of the API documentation (tick-api/README.md) omits the word "token=" from the syntax. It's seen in the example cURL request correctly though. It might be more accurately worded like this:

>Tick uses a simple token-based HTTP Authentication scheme. For clients to authenticate, the method "Token" and the token key should be included in the Authorization HTTP header. The key should be prefixed by the string literal "token=" with no whitespace. For example:

>Authorization: Token token=ApV99yzvwApV99yzvwApV99yzvwApV99yzvw

**Comment by tomrossi7** [comment]
Yeah, the language is hard to get right, but the example code will hopefully make it more clear.  I've gone ahead and updated it.  Thanks for the feedback!
