### ISSUE TITLE
Bad Credentials with every requeset

### ISSUE THREAD

**Issue by thepaleone** [tick/tick-api#7]
I've tried several requests to access the API to no avail. I keep getting the Bad Credentials message. First I tried to use the roles request to retrieve subscription ID's and tokens, but even though I pass the correct email and password (same that I use to log on to the site) I get the bad credentials message:

    curl -k -u "myemail:mypwd" -H "User-Agent: myapp(myurl)" https://www.tickspot.com/api/v2/roles.json
    Bad credentials

Next I went into my user administration (my user is an admin) and got my subscription ID and token from that page. With that I tired several different requests, all of which resulted in the same bad credentials message.

    curl -k -H "User-Agent: myapp(myurl)" -H "Authorization: Token token=mytoken" https://www.tickspot.com/XXXXX/api/v2/projects.json
    Bad credentials

I'm not sure what I"m doing wrong. Is there something that I need to enable on the account to allow API usage?

__Note:__ I've replaced my actual values above with my... or XXXXX. If you need any of that information please let me know privately.

**Comment by tick** [comment]
Check your user agent. Should be a valid email.

**Comment by thepaleone** [comment]
Doh, that was it. For some reason I'd been using a URL rather than an email...thanks for the quick response!

**Comment by tick** [comment]
No problem! I know how frustrating it can be!
