### ISSUE TITLE
Cannot update tasks - 404 error

### ISSUE THREAD

**Issue by jebu75** [tick/tick-api#8]
Trying to use the API got update a task.  Send a PUT request to `https://www.tickspot.com/79434/api/v2/tasks/7359491.json` and I get a 404 response.  I'm reasonably certain my headers are correct as I can create and get tasks, just not update them.

**Comment by tick** [comment]
Thanks for posting your issue!  I checked the logs and found the issue.  We were requiring the project_id as one of the parameters being included.  I've removed that requirement since we really don't need it.  Please let us know if you need anything else!

**Comment by jebu75** [comment]
Thanks for the quick response!  It appears to be successfully updating tasks now.  However, the documentation for updating a task indicates a successful update will return a 200.  I'm getting a 204 which is similar to what the documentation states for a successful DELETE.  I _think_ 204 is the correct code?

**Comment by tick** [comment]
@jebu75 Yeah, there is an inconsistency in our documentation.  There are differing opinions on what should be responded to an HTTP PUT.  Either we return the JSON with a 200, or we return nothing and a 204.  In either case, a 2XX is a successful PUT.  I've made a note about the issue, but I don't think we are ready to commit!

**Comment by jebu75** [comment]
Okay, thanks for the update.
